// <auto-generated />
namespace Clubber.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class join10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(join10));
        
        string IMigrationMetadata.Id
        {
            get { return "201909192058365_join10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
